---
title: "Introduction to R for Data Management and Analysis"
author: "Marcel Ramos, MPH"
date: "Session 7"
output:
  beamer_presentation:
    colortheme: dolphin
    fonttheme: structureitalicserif
    theme: CambridgeUS
  ioslides_presentation: default
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Notes from previous class

* `lm` and friends
* `t-test` with a formula vs vector
* object names with a period (`.`) vs underscore (`_`)
  * method.class (e.g., `cbind.data.frame`)
* 'apply'ing over a `data.frame`

# Today's outline

* General Tips
* Troubleshooting
* Exploratory functions
* Contributing to Open Source Projects
  * GitHub basics
* Data Analysis Workflow

# General R Learning Tips

* Effective troubleshooting is important
    * Get familiar with errors
    * Stack Overflow
    * Helping others on Slack
* Keep inputs and outputs in mind
* Practice, practice, practice
    * Mock examples
    * Answer your own questions in the console
    * Search for answers online
    * Follow online examples by running them
* Make use of online resources, help pages
    * RStudio cheatsheets
* Create your own study sheet

# Study sheet

* Create a study sheet of functions that are useful for a particular task
* Use your reference websites / textbooks
    * [R Cookbook by Winston Chang, 2nd Ed.](https://r-graphics.org/)
    * [Quick-R](https://www.statmethods.net/)
    * [R for Data Science](https://r4ds.had.co.nz/) - Hadley Wickham
    * Handbook for Statistical Analyses using R - 3rd Ed.
* Make use of the resources linked in Trello

# Troubleshooting

* Getting help within R
    * Documentation pages (examples)
* Getting help outside of R
    * stackoverflow.com (link on BB)
        * Reproducible examples `reprex::reprex`
    * Quick-R website
* Finding the error in the code
    * Run code line by line to identify error location
    * Isolate the error by breaking the process into small pieces

# Exploring an object

* `head` & `tail`
* `class`
* `length` or `dim`
* `dimnames`
* `attributes`
* `str`
* `args` on a function

# Data Analysis Workflow

* RStudio setup
* A clean global environment (`.GlobalEnv`)
  * No restoring `.RData`
  * Never save workspace on exit
* (Optional) Avoid the inline RMarkdown results
* Top to bottom RMarkdown
* Import data (usually)
* Clean
    * subset / filter
* Reshape (wide / long)
* summarize / aggregate
* visually explore (EDA)
* graph
  * ggplot2
  * baseR
  * lattice
* Generate the report
  * `knit`ting the document

# Example

* https://www.opencasestudies.org/
    * https://www.opencasestudies.org/ocs-healthexpenditure/
