---
title: "Introduction to R for Data Management and Analysis"
author: "Marcel Ramos"
date: "Tuesday, June 4, 2019"
output:
  beamer_presentation:
    colortheme: dolphin
    fonttheme: structureitalicserif
    theme: CambridgeUS
  ioslides_presentation: default
---

# Introduction to R

\huge{Welcome!}

# Introductions

* Name
* Program/Concentration
* Familiarity with R
* Expectations
* Fun fact?

# Class structure

* Lecture and short exercises: 90 minutes
* Break: 10 minutes
* Exercise: 40 minutes
* Discussion: 10 minutes

# Grading

* Attendance: 15%
* Quizzes: 20%
* Exercises: 65%

# Course Outline

| Date          | Topics                           | Assessment |
|---------------|----------------------------------|------------|
| Tues. June 4  | Introductions                    | -          |
|               | About this class                 |            |
|               | Features of the R language       |            |
|               | Getting help and troubleshooting |            |
|               |                                  |            |
| Thurs. June 6 | Classes and data types           | Exercise   |
|               | data.frame                       |            |
|               | Import/Export                    |            |
|               | subsets                          |            |

# Announcements

* Slack available at \url{https://cunysphcode.slack.com}
* In-person attendance is required
* Syllabus available on Blackboard

# Today's class

* Installation
* R and the RStudio interface
* Basic features of the language
* Getting started
* Tips
* Getting help and troubleshooting
* External resources
* R as a calculator

# What is R?

* R is a programming language and environment for statistical computing and
data visualization
* "Base R" refers to the standalone suite of pre-packaged functions that allow
R to function as a language
* Extensions of the R language are what are called "packages"
* A **package** is a container of functions that give R additional flexibility

# What is RStudio?

* IDE Interactive Development Environment
* Console + Help + Figures + Project Management
* Let's have a look at it!

# What is Git / GitHub?

* GitHub is a public repository of user generated code / analyses
* Provides a foundation for reproducible reports
* Versioning is done using `git`
* The `git` software takes care of versioning of text files

# How do I get started?

* First download the latest R version from [\color{blue}{r-project.org}](https://cloud.r-project.org/)
* Install R with all the default settings
* Download RStudio from [\color{blue}{RStudio.com}](https://www.rstudio.com/products/rstudio/download/)
* RStudio allow you to select the R version installed in your system.

# Recommendations for RStudio setup

* Tools > Global Options
* \color{red}{Don't} restore .RData into workspace
* \color{red}{Never} save workspace to .RData on exit

# Features of the R Language

* case sensitive!!
* Spaces are ignored (except in names)
* works with functions
* vectorized operations
* objects
* help pages
* `?reserved`

# Recognizing a function

* a name followed by parentheses `help()`
* arguments (e.g., `functionname(argument1 = "default")`)
* input / output

# Useful tips for learning R

Pseudo code                                   |   Example code
--------------------------------------------  |   -------------------
install.packages(packagename)                 | install.packages("dplyr")
?functionname                                 | ?select
?package::functionname                        | ?dplyr::select
? 'Reserved keyword or symbol' \color{blue}{(or backticks)} | ? '%>%'
??searchforpossiblyexistingfunctionandortopic | ??simulate
help(package = "loadedpackage")               | help("dplyr")
browseVignettes("packagename")                | browseVignettes("dplyr")

# General tips for learning R

* Learning R will be frustrating
* Learning a language
* Practice promotes familiarity

# R Housekeeping tips

* Maintain a clean R "global" environment
* Save your scripts rather than outputs
* Use object names that are descriptive
* Improve readability with clean formatting

# Getting help and troubleshooting

* Critically important
* "Debugging" your script
* Step by step, line by line process

# First contact with R

* R as a calculator exercise

# External Resources

* [Coursera](https://www.coursera.org)
* [edX](https://www.edX.org)
* [RStudio](https://www.rstudio.com/resources/training/online-learning/#R)
* [Quick-R](http://www.statmethods.net/) -
Mostly for basic and base functions
* [RStudio Cheatcheets](https://www.rstudio.com/resources/cheatsheets/)
